import 'package:admin_tool/features/activity/domain/activity.dart';
import 'package:admin_tool/features/activity/data/activity_repository.dart';
import 'package:admin_tool/features/study_plan/data/study_plan_repository.dart';
import 'package:admin_tool/features/study_plan/domain/study_plan.dart';
import 'package:admin_tool/features/lesson/data/lesson_repository.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:uuid/uuid.dart';

class StudyPlanService {
  final StudyPlanRepository _planRepo;
  final ActivityRepository _activityRepo;
  final LessonRepository _lessonRepo;

  StudyPlanService(this._planRepo, this._activityRepo, this._lessonRepo);

  /// Seeds a standard 26-week study plan based on user's requirements
  Future<void> seedStandardPlan() async {
    const uuid = Uuid();

    // 1. Create or Find Template Activities
    final templateIds = await _ensureTemplateActivities();

    // 2. Create the Plan
    final planId = await _planRepo.createPlan(
      StudyPlan(
        id: '', // Generated by Firestore
        title: 'Lộ trình 6 Tháng (Suomen Mestari 1)',
        description:
            'Lộ trình chuẩn 26 tuần. 3 buổi học chính (Thứ 2, 4, 5). Chủ nhật nghỉ.',
        durationWeeks: 26,
        isDefault: true,
        createdAt: DateTime.now(),
      ),
    );

    // 3. Get Lessons to distribute
    final lessons = await _lessonRepo.getLessonsOnce();

    // 4. Generate 26 Weeks
    for (int w = 1; w <= 26; w++) {
      // Distribution logic: Spread 9 Chapters over 26 weeks.
      // Roughly 3 weeks per chapter (Kappale).
      int chapterNum = ((w - 1) ~/ 2.9).clamp(0, 8) + 1;

      // Find a lesson for this chapter if possible
      String? currentLessonId;
      final chapterLessons = lessons
          .where((l) => l.chapter.contains(chapterNum.toString()))
          .toList();
      if (chapterLessons.isNotEmpty) {
        currentLessonId = chapterLessons[w % chapterLessons.length].id;
      }

      final days = _generateStandardWeekDays(w, currentLessonId, templateIds);

      await _planRepo.createWeek(
        StudyPlanWeek(
          id: uuid.v4(),
          planId: planId,
          weekNumber: w,
          title:
              'Tuần $w: ${chapterLessons.isNotEmpty ? chapterLessons[0].title : "Tổng ôn"}',
          days: days,
        ),
      );
    }
  }

  Future<Map<ActivityType, String>> _ensureTemplateActivities() async {
    final Map<ActivityType, String> map = {};

    final templates = [
      (
        ActivityType.music,
        'Nghe nhạc Phần Lan',
        'Nghe các bài hát để làm quen ngữ điệu.',
      ),
      (
        ActivityType.movie,
        'Xem phim Phần Lan',
        'Xem phim trên Yle Areena hoặc Moomins.',
      ),
      (
        ActivityType.observation,
        'Đọc biển báo / Nghe',
        'Quan sát từ vựng xuất hiện trên đường phố.',
      ),
      (
        ActivityType.writing,
        'Tập viết tay từ mới',
        'Chép tay các từ khó nhớ vào vở.',
      ),
      (
        ActivityType.communication,
        'Giao tiếp hàng ngày',
        'Chào hỏi hoặc hỏi thăm ngắn gọn.',
      ),
      (
        ActivityType.breakTime,
        'Nghỉ ngơi (Break)',
        'Hôm nay hãy nghỉ ngơi thoải mái!',
      ),
    ];

    for (final t in templates) {
      final activity = Activity(
        id: '',
        title: t.$2,
        description: t.$3,
        type: t.$1,
        isPublic: true,
        createdAt: DateTime.now(),
      );

      // We'll create it and record the ID.
      // In a real scenario, we check if title exists.
      final docId = await _activityRepo.createActivityAndGetId(activity);
      map[t.$1] = docId;
    }

    return map;
  }

  List<StudyDay> _generateStandardWeekDays(
    int weekNum,
    String? lessonId,
    Map<ActivityType, String> templates,
  ) {
    // Pattern according to user request:
    // Mon (2), Wed (4), Thu (5): Bài học (Lesson)
    // Sunday (CN): Break

    return [
      StudyDay(
        dayName: 'Maanantai (Thứ 2)',
        activityIds: lessonId != null ? [lessonId] : [],
      ),
      StudyDay(
        dayName: 'Tiistai (Thứ 3)',
        activityIds: [templates[ActivityType.writing] ?? ''],
      ),
      StudyDay(
        dayName: 'Keskiviikko (Thứ 4)',
        activityIds: lessonId != null
            ? [lessonId, templates[ActivityType.music] ?? '']
            : [],
      ),
      StudyDay(
        dayName: 'Torstai (Thứ 5)',
        activityIds: lessonId != null
            ? [lessonId, templates[ActivityType.observation] ?? '']
            : [],
      ),
      StudyDay(
        dayName: 'Perjantai (Thứ 6)',
        activityIds: [templates[ActivityType.communication] ?? ''],
      ),
      StudyDay(
        dayName: 'Lauantai (Thứ 7)',
        activityIds: [templates[ActivityType.movie] ?? ''],
      ),
      StudyDay(
        dayName: 'Sunnuntai (Chủ Nhật)',
        activityIds: [templates[ActivityType.breakTime] ?? ''],
      ),
    ];
  }
}

final studyPlanServiceProvider = Provider(
  (ref) => StudyPlanService(
    ref.watch(studyPlanRepositoryProvider),
    ref.watch(activityRepositoryProvider),
    ref.watch(lessonRepositoryProvider),
  ),
);
